import Nav from '../components/Nav'
import Footer from '../components/Footer'
import styles from './Legal.module.css'

export default function Terms() {
  return (
    <>
      <Nav />
      <main className={styles.page}>
        <div className={styles.kicker}>Legal</div>
        <h1 className={styles.h1}>Terms of Service</h1>
        <div className={styles.meta}>Last updated: May 2026 — Version 1.0</div>

        <div className={styles.notice}>
          These Terms are provided as a working draft for legal review. Obtain legal advice before publishing.
        </div>

        <div className={styles.highlight}>
          Important: LeaseLens is an information and analysis tool. It does not provide legal advice. Nothing generated by this service should be relied upon as a substitute for advice from a qualified Australian solicitor.
        </div>

        <h2>1. Acceptance of terms</h2>
        <p>By accessing or using LeaseLens, you agree to be bound by these Terms of Service and our Privacy Policy.</p>

        <h2>2. Description of service</h2>
        <p>LeaseLens provides AI-powered document analysis for Australian retail lease documents. The service identifies clauses that may carry risk, provides plain-English explanations, suggests negotiation positions, and references relevant legislation.</p>

        <h2>3. Not legal advice</h2>
        <p>All output from this service constitutes general information only. It does not constitute legal advice and does not create a solicitor-client relationship. Always obtain independent legal advice from a qualified Australian solicitor before executing any lease agreement.</p>

        <h2>4. Fees and payment</h2>
        <ul>
          <li>One-off report fees are non-refundable once the analysis has been generated</li>
          <li>Monthly subscriptions renew automatically and may be cancelled at any time</li>
          <li>Cancellation takes effect at the end of the current billing period</li>
          <li>All prices are in Australian dollars inclusive of GST where applicable</li>
        </ul>

        <h2>5. Limitation of liability</h2>
        <p>To the maximum extent permitted by law, our total liability is limited to the amount you paid in the 12 months preceding the claim. Nothing in these Terms excludes rights under the Australian Consumer Law that cannot lawfully be excluded.</p>

        <h2>6. Governing law</h2>
        <p>These Terms are governed by the laws of Western Australia, Australia.</p>

        <h2>7. Contact</h2>
        <p><a href="mailto:hello@leaselens.au">hello@leaselens.au</a> · leaselens.au</p>
      </main>
      <Footer />
    </>
  )
}
