import Nav from '../components/Nav'
import Footer from '../components/Footer'
import styles from './Legal.module.css'

export default function Terms() {
  return (
    <>
      <Nav />
      <main className={styles.page}>
        <div className={styles.kicker}>Legal</div>
        <h1 className={styles.h1}>Terms of Service</h1>
        <div className={styles.meta}>leaseroom.com.au/terms · 16 June 2026</div>

        <div className={styles.notice}>
          These Terms have been prepared for legal review ahead of launch. A solicitor review summary covering the key questions requiring a legal opinion is being finalised separately before the service takes paying customers.
        </div>

        <div className={styles.highlight}>
          Important: LeaseRoom is an information and analysis tool. It does not provide legal or financial advice. Nothing generated by this service should be relied upon as a substitute for advice from a qualified Australian legal practitioner.
        </div>

        <h2>1. Acceptance of terms</h2>
        <p>By accessing or using LeaseRoom you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, do not use the service.</p>
        <p>These Terms are a legally binding agreement between you and Plank Studio Pty Ltd, trading as LeaseRoom (ACN 684 753 731, ABN 37 684 753 731), operating the website at leaseroom.com.au.</p>
        <p>If you are using the service on behalf of a business or organisation, you must have authority to bind that entity to these Terms and to upload documents and materials on its behalf. LeaseRoom provides the service in reliance on that representation.</p>

        <h2>2. Description of service</h2>
        <p>LeaseRoom provides an AI-powered document analysis service for Australian lease documents including heads of agreement, offers to lease, and lease agreements. The service:</p>
        <ul>
          <li>Analyses uploaded documents and identifies clauses that are unusual and that would generally present an apparent risk to the tenant, based on LeaseRoom's proprietary data source as at the date of analysis</li>
          <li>Provides plain-English explanations of identified clauses</li>
          <li>Suggests possible negotiation positions</li>
          <li>References relevant Australian tenancy legislation where applicable</li>
          <li>Generates downloadable PDF reports summarising the analysis</li>
        </ul>
        <p>LeaseRoom does not consider your particular business requirements, circumstances, or objectives. The service analyses documents from a general perspective against its data source only and does not constitute tailored advice.</p>

        <h2>3. Not legal or financial advice</h2>
        <p>All output from the service including analysis reports, risk ratings, clause commentary, and suggested responses constitutes general information only. It does not constitute legal or financial advice.</p>
        <p>LeaseRoom is not a qualified legal practitioner and is not regulated under the Legal Profession Uniform Law or equivalent state or territory legislation. Using the service does not create a solicitor-client relationship.</p>
        <p>You should not rely solely on the service when making decisions about signing or negotiating a lease. We strongly recommend you obtain independent financial advice and independent advice from a qualified Australian legal practitioner before executing any lease agreement or any other agreement.</p>
        <p>We are not liable for, and you release us from, any loss, damage, or adverse outcome arising from your reliance on the service as a substitute for professional legal or financial advice.</p>

        <h2>4. Accuracy and limitations</h2>
        <p>The service uses AI technology. While we take reasonable steps to ensure quality and accuracy, you acknowledge that:</p>
        <ul>
          <li>AI analysis may not identify every relevant clause or risk</li>
          <li>The service analyses only the document as uploaded and cannot identify issues beyond its content</li>
          <li>Suggested negotiation positions are general and may not suit your specific circumstances</li>
          <li>Legislative references are for general guidance and may not reflect the most current law</li>
          <li>Risk ratings are based on LeaseRoom's proprietary data source as at the date of analysis and do not constitute a legal or financial assessment of your specific transaction</li>
        </ul>
        <p>The service is provided on an as-is basis. We do not warrant that the service will be uninterrupted or error-free.</p>

        <h2>5. Your responsibilities</h2>
        <p>You are responsible for:</p>
        <ul>
          <li>Ensuring you have the right to upload and submit documents for analysis</li>
          <li>Checking your confidentiality obligations before uploading, as many documents restrict disclosure to third parties</li>
          <li>Verifying that analysis output is relevant and accurate for your circumstances</li>
          <li>Obtaining independent legal advice before signing any lease or heads of agreement</li>
          <li>Keeping your account credentials secure</li>
        </ul>

        <h2>6. Data and document use</h2>
        <p>When you submit a document for analysis you grant LeaseRoom an irrevocable licence to process that document for the purpose of providing the service.</p>
        <p>Anonymised clause data extracted from your document may be used to improve the LeaseRoom knowledge base. No personally identifying information is retained for this purpose. Full details are in our Privacy Policy.</p>

        <h2>7. Fees, payment and cancellation</h2>
        <p>Subject to the Australian Consumer Law, fees are as displayed on the pricing page at the time of purchase.</p>
        <ul>
          <li>One-off report fees are non-refundable once the analysis has been generated</li>
          <li>Monthly subscriptions are billed in advance and renew automatically unless cancelled</li>
          <li>You may cancel a monthly subscription at any time. Cancellation takes effect at the end of the current billing period with no partial refund for the unused period</li>
          <li>Annual subscriptions are billed upfront for 12 months and are non-refundable except as required by applicable law</li>
          <li>All prices are in Australian dollars inclusive of GST where applicable</li>
        </ul>
        <p>Payments are processed by Stripe. We do not store your card details.</p>

        <h2>8. Limitation of liability</h2>
        <p>To the maximum extent permitted by law, our total liability for any claim arising from use of the service is limited to the amount you paid to us in the 12 months before the claim arose.</p>
        <p>To the maximum extent permitted by law, we exclude liability for indirect, incidental, or consequential loss, loss of profits or business opportunity, loss arising from reliance on service output without obtaining independent advice, and loss arising from a clause or risk not identified by the service.</p>
        <p>Nothing in these Terms excludes any guarantee, warranty, or right that cannot lawfully be excluded under the Australian Consumer Law. Where the Australian Consumer Law applies, our liability is limited to the extent permitted by law to resupply of the service or payment of the cost of resupply.</p>

        <h2>9. Intellectual property</h2>
        <p>All content, methodology, knowledge base, prompts, design, and reports produced by LeaseRoom are our intellectual property. You may not reproduce, distribute, or create derivative works without our written permission.</p>
        <p>You retain ownership of documents you upload. You grant us a limited licence to process those documents as set out in clause 6.</p>

        <h2>10. Professional use restriction</h2>
        <p>Individual monthly and annual plans are for personal use only. Using an individual plan to provide analysis services to third-party clients on a commercial basis is not permitted and constitutes a breach of these Terms.</p>

        <h2>11. Termination</h2>
        <p>We may suspend or terminate your access at any time if you breach these Terms or engage in fraudulent activity. We will provide notice where practicable. You may terminate your account at any time by contacting us at <a href="mailto:hello@leaseroom.com.au">hello@leaseroom.com.au</a>.</p>

        <h2>12. Changes to terms</h2>
        <p>We may update these Terms from time to time. We will notify you of material changes by email or by notice on the website. Continued use of the service after the effective date of any changes constitutes acceptance of the updated Terms.</p>

        <h2>13. Governing law</h2>
        <p>These Terms are governed by the laws of Western Australia, Australia. You submit to the non-exclusive jurisdiction of the courts of Western Australia.</p>

        <h2>14. Contact</h2>
        <div className={styles.contactBlock}>
          <strong>Entity:</strong> Plank Studio Pty Ltd, trading as LeaseRoom<br />
          ACN 684 753 731 &nbsp;|&nbsp; ABN 37 684 753 731<br />
          Email: <a href="mailto:hello@leaseroom.com.au">hello@leaseroom.com.au</a><br />
          Website: <a href="https://www.leaseroom.com.au" target="_blank" rel="noopener noreferrer">www.leaseroom.com.au</a>
        </div>
      </main>
      <Footer />
    </>
  )
}
